name: Create Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup jdk 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: make gradle wrapper executable
        run: chmod +x ./gradlecw
      - name: build
        run: ./gradlecw build -Pbuild.release=true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'versions/**/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
      - name: Publish-1.20.1-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v2.0.2
        with:
          curseforge-id: 882472
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: Branded Logs v${{github.ref_name}}
          files: 'versions/1.20.1-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.1
      - name: Publish-1.20.1-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v2.0.2
        with:
          modrinth-id: tbktcZz2
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: Branded Logs v${{github.ref_name}}
          files: 'versions/1.20.1-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.1
      - name: Publish-1.20.2-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v2.0.2
        with:
          curseforge-id: 882472
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: Branded Logs v${{github.ref_name}}
          files: 'versions/1.20.2-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.2
      - name: Publish-1.20.2-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v2.0.2
        with:
          modrinth-id: tbktcZz2
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: Branded Logs v${{github.ref_name}}
          files: 'versions/1.20.2-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.2
      - name: Publish-1.20.2-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v2.0.2
        with:
          curseforge-id: 882472
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: Branded Logs v${{github.ref_name}}
          files: 'versions/1.20.2-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.2
      - name: Publish-1.20.2-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v2.0.2
        with:
          modrinth-id: tbktcZz2
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: Branded Logs v${{github.ref_name}}
          files: 'versions/1.20.2-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.2
      - name: Publish-1.20.4-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v2.0.2
        with:
          curseforge-id: 882472
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: Branded Logs v${{github.ref_name}}
          files: 'versions/1.20.4-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.4
      - name: Publish-1.20.4-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v2.0.2
        with:
          modrinth-id: tbktcZz2
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: Branded Logs v${{github.ref_name}}
          files: 'versions/1.20.4-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.4
      - name: Publish-1.20.6-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v2.0.2
        with:
          curseforge-id: 882472
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: Branded Logs v${{github.ref_name}}
          files: 'versions/1.20.6-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.6
      - name: Publish-1.20.6-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v2.0.2
        with:
          modrinth-id: tbktcZz2
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: Branded Logs v${{github.ref_name}}
          files: 'versions/1.20.6-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.6
      - name: Publish-1.21-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v2.0.2
        with:
          curseforge-id: 882472
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: Branded Logs v${{github.ref_name}}
          files: 'versions/1.21-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.21
      - name: Publish-1.21-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v2.0.2
        with:
          modrinth-id: tbktcZz2
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: Branded Logs v${{github.ref_name}}
          files: 'versions/1.21-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.21
